# This workflow checks Trello every 5 minutes for new board actions,
# and sends updates to a Discord webhook.
# It caches the last check timestamp using GitHub Actions cache.

name: Trello to Discord Notifier

permissions:
  contents: read

on:
  schedule:
    - cron: '*/5 * * * *' # every 5 minutes
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Restore last Trello check time from cache
        id: cache-last-check
        uses: actions/cache@v4
        with:
          path: .last_trello_check
          key: last-trello-check
          restore-keys: |
            last-trello-check

      - name: Set default last check time if not cached
        run: |
          if [ ! -f .last_trello_check ]; then
            echo "1970-01-01T00:00:00Z" > .last_trello_check
          fi

      - name: Read last check time
        run: |
          LAST=$(cat .last_trello_check)
          echo "LAST=$LAST" >> "$GITHUB_ENV"

      - name: Fetch recent actions from Trello
        id: fetch
        env:
          TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
          TRELLO_TOKEN: ${{ secrets.TRELLO_TOKEN }}
          TRELLO_BOARD_ID: ${{ secrets.TRELLO_BOARD_ID }}
        run: |
          curl -s "https://api.trello.com/1/boards/$TRELLO_BOARD_ID/actions?key=$TRELLO_API_KEY&token=$TRELLO_TOKEN&limit=10" > trello_response_raw.txt
          echo "Trello API raw response:"
          cat trello_response_raw.txt
          LAST=$(cat .last_trello_check)
          jq --arg last "$LAST" '[.[] | select(.date > $last)]' trello_response_raw.txt > new_actions.json          

      - name: Notify Discord
        if: success()
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          count=$(jq length new_actions.json)
          if [ "$count" -eq 0 ]; then
            echo "No new actions."
            exit 0
          fi

          messages=$(jq -r '.[] | "\(.memberCreator.fullName // "Unknown user") performed \(.type) on \(.data.card.name // "Unnamed card")"' new_actions.json)
          
          payload=$(echo -e "Trello updates:\n$messages" | jq -Rs .)
          
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": $payload}" \
               "$DISCORD_WEBHOOK_URL"

      - name: Update last Trello check timestamp
        run: date -u +"%Y-%m-%dT%H:%M:%SZ" > .last_trello_check

      - name: Save updated last Trello check to cache
        uses: actions/cache/save@v4
        with:
          path: .last_trello_check
          key: last-trello-check
